// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTracker.Data;

namespace WorkoutTracker.Data.Migrations
{
    [DbContext(typeof(WorkoutsContext))]
    [Migration("20190813141159_ExerciseAdditions")]
    partial class ExerciseAdditions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkoutTracker.Domain.Exercises.ExecutedExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<int?>("ExerciseId");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096);

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("ExecutedExercises");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Exercises.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096);

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasMaxLength(4096);

                    b.Property<string>("Name");

                    b.Property<string>("PointsToRemember")
                        .HasMaxLength(4096);

                    b.Property<string>("Setup")
                        .HasMaxLength(4096);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Exercises.ExerciseInWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<int?>("ExerciseId");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<short>("NumberOfSets");

                    b.Property<int>("SetType");

                    b.Property<int?>("WorkoutId");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseInWorkout");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Exercises.ExerciseTargetAreaLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<int>("ExerciseId");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<int>("TargetAreaId");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TargetAreaId");

                    b.ToTable("ExerciseTargetAreaLinks");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Exercises.TargetArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("TargetAreas");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Resistances.Resistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("ExecutedExerciseId");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedExerciseId");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("Resistances");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Resistance");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Resistances.ResistanceBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<decimal>("ResistanceAmount");

                    b.HasKey("Id");

                    b.HasIndex("Color");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("ResistanceBands");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Sets.ExecutedSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("ExecutedExerciseId");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<int?>("SetId");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedExerciseId");

                    b.HasIndex("SetId");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("ExecutedSets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ExecutedSet");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Sets.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("ExerciseId");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<short>("Sequence");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("Sets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Set");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("HashedPassword")
                        .HasMaxLength(1024);

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ProfilePic")
                        .HasMaxLength(4096);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Workouts.ExecutedWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<string>("Journal");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<int>("Rating");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<int?>("WorkoutId");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExecutedWorkouts");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Workouts.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<int?>("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedDateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId", "CreatedDateTime", "ModifiedByUserId", "ModifiedDateTime");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Resistances.BandResistance", b =>
                {
                    b.HasBaseType("WorkoutTracker.Domain.Resistances.Resistance");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasIndex("Amount");

                    b.HasIndex("Color");

                    b.HasDiscriminator().HasValue("BandResistance");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Sets.ExecutedRepetitionSet", b =>
                {
                    b.HasBaseType("WorkoutTracker.Domain.Sets.ExecutedSet");

                    b.Property<int>("ExecutedRepCount");

                    b.HasDiscriminator().HasValue("ExecutedRepetitionSet");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Sets.ExecutedTimedSet", b =>
                {
                    b.HasBaseType("WorkoutTracker.Domain.Sets.ExecutedSet");

                    b.Property<TimeSpan>("ExecutedTime");

                    b.HasDiscriminator().HasValue("ExecutedTimedSet");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Sets.RepetitionSet", b =>
                {
                    b.HasBaseType("WorkoutTracker.Domain.Sets.Set");

                    b.Property<int>("TargetRepCount");

                    b.HasDiscriminator().HasValue("RepetitionSet");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Sets.TimedSet", b =>
                {
                    b.HasBaseType("WorkoutTracker.Domain.Sets.Set");

                    b.Property<TimeSpan>("TargetTime");

                    b.HasDiscriminator().HasValue("TimedSet");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Exercises.ExecutedExercise", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Exercises.ExerciseInWorkout", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");

                    b.HasOne("WorkoutTracker.Domain.Workouts.Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Exercises.ExerciseTargetAreaLink", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseTargetAreaLinks")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorkoutTracker.Domain.Exercises.TargetArea", "TargetArea")
                        .WithMany()
                        .HasForeignKey("TargetAreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Resistances.Resistance", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Exercises.ExecutedExercise")
                        .WithMany("Resistances")
                        .HasForeignKey("ExecutedExerciseId");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Sets.ExecutedSet", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Exercises.ExecutedExercise", "ExecutedExercise")
                        .WithMany()
                        .HasForeignKey("ExecutedExerciseId");

                    b.HasOne("WorkoutTracker.Domain.Sets.Set", "Set")
                        .WithMany()
                        .HasForeignKey("SetId");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Sets.Set", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Workouts.ExecutedWorkout", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Workouts.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId");
                });
#pragma warning restore 612, 618
        }
    }
}
