// This file is auto-generated by @hey-api/openapi-ts

import type { GetApiAnalyticsExecutedWorkoutsResponse, GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponse, GetApiExecutedWorkoutByPublicIdResponse, GetApiExecutedWorkoutInProgressResponse, GetApiExecutedWorkoutPlannedResponse, GetApiExecutedWorkoutResponse, GetApiExercisesByPublicIdResponse, GetApiExercisesResponse, GetApiResistanceBandsByIdResponse, GetApiResistanceBandsResponse, GetApiTargetAreasByIdResponse, GetApiTargetAreasResponse, GetApiUsersByIdResponse, GetApiUsersByPublicIdResponse, GetApiUsersOverviewResponse, GetApiUsersResponse, GetApiWorkoutsByPublicIdResponse, GetApiWorkoutsByWorkoutPublicIdPlanResponse, GetApiWorkoutsResponse, PostApiExercisesResponse, PostApiResistanceBandsResponse, PostApiTargetAreasResponse, PostApiUsersNewResponse, PostApiUsersResponse, PostApiWorkoutsResponse, PutApiExecutedWorkoutByIdResponse, PutApiExercisesResponse, PutApiResistanceBandsByIdResponse, PutApiTargetAreasByIdResponse, PutApiUsersByIdResponse, PutApiWorkoutsResponse } from './types.gen';

const executedWorkoutsSummarySchemaResponseTransformer = (data: any) => {
    if (data.firstLoggedWorkoutDateTime) {
        data.firstLoggedWorkoutDateTime = new Date(data.firstLoggedWorkoutDateTime);
    }
    return data;
};

export const getApiAnalyticsExecutedWorkoutsResponseTransformer = async (data: any): Promise<GetApiAnalyticsExecutedWorkoutsResponse> => {
    data = executedWorkoutsSummarySchemaResponseTransformer(data);
    return data;
};

const executedWorkoutMetricsSchemaResponseTransformer = (data: any) => {
    data.startDateTime = new Date(data.startDateTime);
    data.endDateTime = new Date(data.endDateTime);
    return data;
};

export const getApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponseTransformer = async (data: any): Promise<GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponse> => {
    data = data.map((item: any) => executedWorkoutMetricsSchemaResponseTransformer(item));
    return data;
};

const executedExerciseDtoSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    return data;
};

const executedWorkoutDtoSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    if (data.startDateTime) {
        data.startDateTime = new Date(data.startDateTime);
    }
    if (data.endDateTime) {
        data.endDateTime = new Date(data.endDateTime);
    }
    if (data.exercises) {
        data.exercises = data.exercises.map((item: any) => executedExerciseDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const getApiExecutedWorkoutByPublicIdResponseTransformer = async (data: any): Promise<GetApiExecutedWorkoutByPublicIdResponse> => {
    data = executedWorkoutDtoSchemaResponseTransformer(data);
    return data;
};

export const putApiExecutedWorkoutByIdResponseTransformer = async (data: any): Promise<PutApiExecutedWorkoutByIdResponse> => {
    data = executedWorkoutDtoSchemaResponseTransformer(data);
    return data;
};

const executedWorkoutSummaryDtoSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    if (data.startDateTime) {
        data.startDateTime = new Date(data.startDateTime);
    }
    if (data.endDateTime) {
        data.endDateTime = new Date(data.endDateTime);
    }
    return data;
};

const executedWorkoutSummaryDtoPaginatedResultsSchemaResponseTransformer = (data: any) => {
    if (data.results) {
        data.results = data.results.map((item: any) => executedWorkoutSummaryDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const getApiExecutedWorkoutResponseTransformer = async (data: any): Promise<GetApiExecutedWorkoutResponse> => {
    data = executedWorkoutSummaryDtoPaginatedResultsSchemaResponseTransformer(data);
    return data;
};

export const getApiExecutedWorkoutPlannedResponseTransformer = async (data: any): Promise<GetApiExecutedWorkoutPlannedResponse> => {
    data = executedWorkoutSummaryDtoPaginatedResultsSchemaResponseTransformer(data);
    return data;
};

export const getApiExecutedWorkoutInProgressResponseTransformer = async (data: any): Promise<GetApiExecutedWorkoutInProgressResponse> => {
    data = data.map((item: any) => executedWorkoutSummaryDtoSchemaResponseTransformer(item));
    return data;
};

const exerciseDtoSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    return data;
};

const exerciseDtoPaginatedResultsSchemaResponseTransformer = (data: any) => {
    if (data.results) {
        data.results = data.results.map((item: any) => exerciseDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const getApiExercisesResponseTransformer = async (data: any): Promise<GetApiExercisesResponse> => {
    data = exerciseDtoPaginatedResultsSchemaResponseTransformer(data);
    return data;
};

const targetAreaSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    return data;
};

const exerciseTargetAreaLinkSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    if (data.exercise) {
        data.exercise = exerciseSchemaResponseTransformer(data.exercise);
    }
    if (data.targetArea) {
        data.targetArea = targetAreaSchemaResponseTransformer(data.targetArea);
    }
    return data;
};

const exerciseSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    if (data.exerciseTargetAreaLinks) {
        data.exerciseTargetAreaLinks = data.exerciseTargetAreaLinks.map((item: any) => exerciseTargetAreaLinkSchemaResponseTransformer(item));
    }
    return data;
};

export const postApiExercisesResponseTransformer = async (data: any): Promise<PostApiExercisesResponse> => {
    data = exerciseSchemaResponseTransformer(data);
    return data;
};

export const putApiExercisesResponseTransformer = async (data: any): Promise<PutApiExercisesResponse> => {
    data = exerciseSchemaResponseTransformer(data);
    return data;
};

export const getApiExercisesByPublicIdResponseTransformer = async (data: any): Promise<GetApiExercisesByPublicIdResponse> => {
    data = exerciseSchemaResponseTransformer(data);
    return data;
};

const resistanceBandSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    return data;
};

export const getApiResistanceBandsResponseTransformer = async (data: any): Promise<GetApiResistanceBandsResponse> => {
    data = data.map((item: any) => resistanceBandSchemaResponseTransformer(item));
    return data;
};

export const postApiResistanceBandsResponseTransformer = async (data: any): Promise<PostApiResistanceBandsResponse> => {
    data = resistanceBandSchemaResponseTransformer(data);
    return data;
};

export const getApiResistanceBandsByIdResponseTransformer = async (data: any): Promise<GetApiResistanceBandsByIdResponse> => {
    data = resistanceBandSchemaResponseTransformer(data);
    return data;
};

export const putApiResistanceBandsByIdResponseTransformer = async (data: any): Promise<PutApiResistanceBandsByIdResponse> => {
    data = resistanceBandSchemaResponseTransformer(data);
    return data;
};

export const getApiTargetAreasResponseTransformer = async (data: any): Promise<GetApiTargetAreasResponse> => {
    data = data.map((item: any) => targetAreaSchemaResponseTransformer(item));
    return data;
};

export const postApiTargetAreasResponseTransformer = async (data: any): Promise<PostApiTargetAreasResponse> => {
    data = targetAreaSchemaResponseTransformer(data);
    return data;
};

export const getApiTargetAreasByIdResponseTransformer = async (data: any): Promise<GetApiTargetAreasByIdResponse> => {
    data = targetAreaSchemaResponseTransformer(data);
    return data;
};

export const putApiTargetAreasByIdResponseTransformer = async (data: any): Promise<PutApiTargetAreasByIdResponse> => {
    data = targetAreaSchemaResponseTransformer(data);
    return data;
};

const userMinMaxRepsSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    return data;
};

const userSettingsSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    if (data.repSettings) {
        data.repSettings = data.repSettings.map((item: any) => userMinMaxRepsSchemaResponseTransformer(item));
    }
    return data;
};

const userSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    if (data.settings) {
        data.settings = userSettingsSchemaResponseTransformer(data.settings);
    }
    return data;
};

export const getApiUsersByPublicIdResponseTransformer = async (data: any): Promise<GetApiUsersByPublicIdResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const getApiUsersResponseTransformer = async (data: any): Promise<GetApiUsersResponse> => {
    data = data.map((item: any) => userSchemaResponseTransformer(item));
    return data;
};

export const postApiUsersResponseTransformer = async (data: any): Promise<PostApiUsersResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const postApiUsersNewResponseTransformer = async (data: any): Promise<PostApiUsersNewResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const userOverviewSchemaResponseTransformer = (data: any) => {
    if (data.lastWorkoutDateTime) {
        data.lastWorkoutDateTime = new Date(data.lastWorkoutDateTime);
    }
    return data;
};

export const getApiUsersOverviewResponseTransformer = async (data: any): Promise<GetApiUsersOverviewResponse> => {
    data = userOverviewSchemaResponseTransformer(data);
    return data;
};

export const getApiUsersByIdResponseTransformer = async (data: any): Promise<GetApiUsersByIdResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const putApiUsersByIdResponseTransformer = async (data: any): Promise<PutApiUsersByIdResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const workoutDtoSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    return data;
};

const workoutDtoPaginatedResultsSchemaResponseTransformer = (data: any) => {
    if (data.results) {
        data.results = data.results.map((item: any) => workoutDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const getApiWorkoutsResponseTransformer = async (data: any): Promise<GetApiWorkoutsResponse> => {
    data = workoutDtoPaginatedResultsSchemaResponseTransformer(data);
    return data;
};

const exerciseInWorkoutSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    if (data.exercise) {
        data.exercise = exerciseSchemaResponseTransformer(data.exercise);
    }
    return data;
};

const workoutSchemaResponseTransformer = (data: any) => {
    data.createdDateTime = new Date(data.createdDateTime);
    if (data.modifiedDateTime) {
        data.modifiedDateTime = new Date(data.modifiedDateTime);
    }
    if (data.exercises) {
        data.exercises = data.exercises.map((item: any) => exerciseInWorkoutSchemaResponseTransformer(item));
    }
    return data;
};

export const postApiWorkoutsResponseTransformer = async (data: any): Promise<PostApiWorkoutsResponse> => {
    data = workoutSchemaResponseTransformer(data);
    return data;
};

export const putApiWorkoutsResponseTransformer = async (data: any): Promise<PutApiWorkoutsResponse> => {
    data = workoutSchemaResponseTransformer(data);
    return data;
};

export const getApiWorkoutsByPublicIdResponseTransformer = async (data: any): Promise<GetApiWorkoutsByPublicIdResponse> => {
    data = workoutSchemaResponseTransformer(data);
    return data;
};

const workoutPlanSchemaResponseTransformer = (data: any) => {
    if (data.submittedDateTime) {
        data.submittedDateTime = new Date(data.submittedDateTime);
    }
    return data;
};

export const getApiWorkoutsByWorkoutPublicIdPlanResponseTransformer = async (data: any): Promise<GetApiWorkoutsByWorkoutPublicIdPlanResponse> => {
    data = workoutPlanSchemaResponseTransformer(data);
    return data;
};
