// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5600' | (string & {});
};

export type ExecutedExerciseDto = {
    id: number;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name?: string | null;
    exerciseId: string;
    resistanceType: ResistanceType;
    sequence: number;
    targetRepCount: number;
    actualRepCount: number;
    notes?: string | null;
    resistanceAmount: number;
    resistanceMakeup?: string | null;
    setType: SetType;
    duration?: number | null;
    formRating: number;
    rangeOfMotionRating: number;
    bandsEndToEnd?: boolean | null;
    involvesReps: boolean;
    side?: ExerciseSide | null;
    usesBilateralResistance: boolean;
};

export type ExecutedExerciseMetrics = {
    exerciseId: string;
    name?: string | null;
    sequence: number;
    setType: SetType;
    averageRepCount: number;
    averageResistanceAmount: number;
    averageForm: number;
    averageRangeOfMotion: number;
};

export type ExecutedWorkoutDto = {
    id: string;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name?: string | null;
    workoutId: string;
    startDateTime?: Date | null;
    endDateTime?: Date | null;
    journal?: string | null;
    rating: number;
    exercises?: Array<ExecutedExerciseDto> | null;
};

export type ExecutedWorkoutMetrics = {
    name?: string | null;
    startDateTime: Date;
    endDateTime: Date;
    exerciseMetrics?: Array<ExecutedExerciseMetrics> | null;
};

export type ExecutedWorkoutSummaryDto = {
    id: string;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name?: string | null;
    workoutPublicId: string;
    startDateTime?: Date | null;
    endDateTime?: Date | null;
    journal?: string | null;
};

export type ExecutedWorkoutSummaryDtoPaginatedResults = {
    results?: Array<ExecutedWorkoutSummaryDto> | null;
    totalCount: number;
};

export type ExecutedWorkoutsSummary = {
    totalLoggedWorkouts: number;
    firstLoggedWorkoutDateTime?: Date | null;
    targetAreasWithWorkoutCounts?: {
        [key: string]: number;
    } | null;
};

export type Exercise = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name?: string | null;
    publicId: string;
    description?: string | null;
    setup?: string | null;
    movement?: string | null;
    pointsToRemember?: string | null;
    exerciseTargetAreaLinks?: Array<ExerciseTargetAreaLink> | null;
    resistanceType: ResistanceType;
    oneSided: boolean;
    bandsEndToEnd?: boolean | null;
    involvesReps: boolean;
    usesBilateralResistance: boolean;
};

export type ExerciseDto = {
    id: number;
    publicId: string;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name?: string | null;
    targetAreas?: string | null;
};

export type ExerciseDtoPaginatedResults = {
    results?: Array<ExerciseDto> | null;
    totalCount: number;
};

export type ExerciseInWorkout = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    exercise?: Exercise | null;
    exerciseId: number;
    numberOfSets: number;
    setType: SetType;
    sequence: number;
};

export type ExerciseInWorkoutDto = {
    id: number;
    exerciseId: string;
    exerciseName?: string | null;
    numberOfSets: number;
    setType: SetType;
    resistanceType: ResistanceType;
};

export type ExercisePlan = {
    exerciseInWorkoutId: number;
    exerciseId: number;
    exerciseName?: string | null;
    numberOfSets: number;
    setType: SetType;
    resistanceType: ResistanceType;
    sequence: number;
    targetRepCountLastTime: number;
    maxActualRepCountLastTime: number;
    avgActualRepCountLastTime: number;
    maxRangeOfMotionLastTime: number;
    avgRangeOfMotionLastTime: number;
    maxFormLastTime: number;
    avgFormLastTime: number;
    recommendedTargetRepCount?: number | null;
    targetRepCount: number;
    resistanceAmountLastTime: number;
    resistanceMakeupLastTime?: string | null;
    recommendedResistanceAmount?: number | null;
    recommendedResistanceMakeup?: string | null;
    resistanceAmount: number;
    resistanceMakeup?: string | null;
    bandsEndToEnd?: boolean | null;
    involvesReps: boolean;
    usesBilateralResistance: boolean;
    recommendationReason?: string | null;
};

export type ExerciseSide = 0 | 1;

export type ExerciseTargetAreaLink = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    exerciseId: number;
    targetAreaId: number;
    exercise?: Exercise | null;
    targetArea?: TargetArea | null;
};

export type PasswordChangeRequest = {
    currentPassword?: string | null;
    newPassword?: string | null;
};

export type PasswordResetRequest = {
    resetCode?: string | null;
    newPassword?: string | null;
};

export type RequestPasswordResetRequest = {
    emailAddress?: string | null;
};

export type ResistanceBand = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    color?: string | null;
    maxResistanceAmount: number;
    numberAvailable: number;
    publicId: string;
};

export type ResistanceType = 0 | 1 | 2 | 3 | 4;

export type SetType = 0 | 1;

export type TargetArea = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name?: string | null;
};

export type User = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name?: string | null;
    publicId: string;
    emailAddress?: string | null;
    hashedPassword?: string | null;
    profilePic?: string | null;
    settings?: UserSettings | null;
    role: UserRole;
    salt?: string | null;
    passwordResetCode?: string | null;
    readonly passwordProtected: boolean;
};

export type UserCredentialsDto = {
    username: string;
    password?: string | null;
};

export type UserMinMaxReps = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    userSettingsId: number;
    setType: SetType;
    duration?: number | null;
    minReps: number;
    maxReps: number;
};

export type UserNewDto = {
    userName?: string | null;
    emailAddress?: string | null;
    password?: string | null;
    role: UserRole;
};

export type UserOverview = {
    username?: string | null;
    lastWorkoutDateTime?: Date | null;
    plannedWorkoutCount: number;
};

export type UserRole = 1 | 2;

export type UserSettings = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    userId: number;
    repSettings?: Array<UserMinMaxReps> | null;
    recommendationsEnabled: boolean;
    lowestAcceptableRating: number;
};

export type Workout = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name?: string | null;
    publicId: string;
    exercises?: Array<ExerciseInWorkout> | null;
    active: boolean;
};

export type WorkoutDto = {
    id: string;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name?: string | null;
    exercises?: Array<ExerciseInWorkoutDto> | null;
    targetAreas?: string | null;
    active: boolean;
};

export type WorkoutDtoPaginatedResults = {
    results?: Array<WorkoutDto> | null;
    totalCount: number;
};

export type WorkoutPlan = {
    workoutId: string;
    workoutName?: string | null;
    hasBeenExecutedBefore: boolean;
    exercises?: Array<ExercisePlan> | null;
    submittedDateTime?: Date | null;
};

export type UserWritable = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name?: string | null;
    publicId: string;
    emailAddress?: string | null;
    hashedPassword?: string | null;
    profilePic?: string | null;
    settings?: UserSettings | null;
    role: UserRole;
    salt?: string | null;
    passwordResetCode?: string | null;
};

export type GetApiAnalyticsExecutedWorkoutsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Analytics/executed-workouts';
};

export type GetApiAnalyticsExecutedWorkoutsResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutsSummary;
};

export type GetApiAnalyticsExecutedWorkoutsResponse = GetApiAnalyticsExecutedWorkoutsResponses[keyof GetApiAnalyticsExecutedWorkoutsResponses];

export type GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountData = {
    body?: never;
    path: {
        workoutPublicId: string;
        count: number;
    };
    query?: never;
    url: '/api/Analytics/workout-metrics/{workoutPublicId}/{count}';
};

export type GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponses = {
    /**
     * OK
     */
    200: Array<ExecutedWorkoutMetrics>;
};

export type GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponse = GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponses[keyof GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponses];

export type PostApiAuthLoginData = {
    body?: UserCredentialsDto;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthChangePasswordData = {
    body?: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/change-password';
};

export type PostApiAuthChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthRequestPasswordResetData = {
    body?: RequestPasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/request-password-reset';
};

export type PostApiAuthRequestPasswordResetResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiAuthRequestPasswordResetResponse = PostApiAuthRequestPasswordResetResponses[keyof PostApiAuthRequestPasswordResetResponses];

export type PostApiAuthResetPasswordData = {
    body?: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/reset-password';
};

export type PostApiAuthResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAuthValidateResetCodeByResetCodeData = {
    body?: never;
    path: {
        resetCode: string;
    };
    query?: never;
    url: '/api/Auth/validate-reset-code/{resetCode}';
};

export type GetApiAuthValidateResetCodeByResetCodeResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetApiAuthValidateResetCodeByResetCodeResponse = GetApiAuthValidateResetCodeByResetCodeResponses[keyof GetApiAuthValidateResetCodeByResetCodeResponses];

export type GetApiExecutedWorkoutByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/ExecutedWorkout/{publicId}';
};

export type GetApiExecutedWorkoutByPublicIdResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutDto;
};

export type GetApiExecutedWorkoutByPublicIdResponse = GetApiExecutedWorkoutByPublicIdResponses[keyof GetApiExecutedWorkoutByPublicIdResponses];

export type PutApiExecutedWorkoutByIdData = {
    body?: ExecutedWorkoutDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ExecutedWorkout/{id}';
};

export type PutApiExecutedWorkoutByIdResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutDto;
};

export type PutApiExecutedWorkoutByIdResponse = PutApiExecutedWorkoutByIdResponses[keyof PutApiExecutedWorkoutByIdResponses];

export type GetApiExecutedWorkoutData = {
    body?: never;
    path?: never;
    query?: {
        firstRecord?: number;
        pageSize?: number;
        startDateTime?: Date;
        endDateTime?: Date;
        newestFirst?: boolean;
        workoutNameContains?: string;
    };
    url: '/api/ExecutedWorkout';
};

export type GetApiExecutedWorkoutResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutSummaryDtoPaginatedResults;
};

export type GetApiExecutedWorkoutResponse = GetApiExecutedWorkoutResponses[keyof GetApiExecutedWorkoutResponses];

export type GetApiExecutedWorkoutPlannedData = {
    body?: never;
    path?: never;
    query?: {
        firstRecord?: number;
        pageSize?: number;
        newestFirst?: boolean;
    };
    url: '/api/ExecutedWorkout/planned';
};

export type GetApiExecutedWorkoutPlannedResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutSummaryDtoPaginatedResults;
};

export type GetApiExecutedWorkoutPlannedResponse = GetApiExecutedWorkoutPlannedResponses[keyof GetApiExecutedWorkoutPlannedResponses];

export type GetApiExecutedWorkoutInProgressData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ExecutedWorkout/in-progress';
};

export type GetApiExecutedWorkoutInProgressResponses = {
    /**
     * OK
     */
    200: Array<ExecutedWorkoutSummaryDto>;
};

export type GetApiExecutedWorkoutInProgressResponse = GetApiExecutedWorkoutInProgressResponses[keyof GetApiExecutedWorkoutInProgressResponses];

export type DeleteApiExecutedWorkoutPlannedByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/ExecutedWorkout/planned/{publicId}';
};

export type DeleteApiExecutedWorkoutPlannedByPublicIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiExercisesData = {
    body?: never;
    path?: never;
    query?: {
        firstRecord?: number;
        pageSize?: number;
        nameContains?: string;
        hasTargetAreas?: string;
    };
    url: '/api/Exercises';
};

export type GetApiExercisesResponses = {
    /**
     * OK
     */
    200: ExerciseDtoPaginatedResults;
};

export type GetApiExercisesResponse = GetApiExercisesResponses[keyof GetApiExercisesResponses];

export type PostApiExercisesData = {
    body?: Exercise;
    path?: never;
    query?: never;
    url: '/api/Exercises';
};

export type PostApiExercisesResponses = {
    /**
     * OK
     */
    200: Exercise;
};

export type PostApiExercisesResponse = PostApiExercisesResponses[keyof PostApiExercisesResponses];

export type PutApiExercisesData = {
    body?: Exercise;
    path?: never;
    query?: never;
    url: '/api/Exercises';
};

export type PutApiExercisesResponses = {
    /**
     * OK
     */
    200: Exercise;
};

export type PutApiExercisesResponse = PutApiExercisesResponses[keyof PutApiExercisesResponses];

export type DeleteApiExercisesByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Exercises/{publicId}';
};

export type DeleteApiExercisesByPublicIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiExercisesByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Exercises/{publicId}';
};

export type GetApiExercisesByPublicIdResponses = {
    /**
     * OK
     */
    200: Exercise;
};

export type GetApiExercisesByPublicIdResponse = GetApiExercisesByPublicIdResponses[keyof GetApiExercisesByPublicIdResponses];

export type GetApiExercisesResistanceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Exercises/ResistanceTypes';
};

export type GetApiExercisesResistanceTypesResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetApiExercisesResistanceTypesResponse = GetApiExercisesResistanceTypesResponses[keyof GetApiExercisesResistanceTypesResponses];

export type GetApiResistanceBandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ResistanceBands';
};

export type GetApiResistanceBandsResponses = {
    /**
     * OK
     */
    200: Array<ResistanceBand>;
};

export type GetApiResistanceBandsResponse = GetApiResistanceBandsResponses[keyof GetApiResistanceBandsResponses];

export type PostApiResistanceBandsData = {
    body?: ResistanceBand;
    path?: never;
    query?: {
        setAuditFields?: boolean;
    };
    url: '/api/ResistanceBands';
};

export type PostApiResistanceBandsResponses = {
    /**
     * OK
     */
    200: ResistanceBand;
};

export type PostApiResistanceBandsResponse = PostApiResistanceBandsResponses[keyof PostApiResistanceBandsResponses];

export type DeleteApiResistanceBandsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/ResistanceBands/{id}';
};

export type DeleteApiResistanceBandsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiResistanceBandsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/ResistanceBands/{id}';
};

export type GetApiResistanceBandsByIdResponses = {
    /**
     * OK
     */
    200: ResistanceBand;
};

export type GetApiResistanceBandsByIdResponse = GetApiResistanceBandsByIdResponses[keyof GetApiResistanceBandsByIdResponses];

export type PutApiResistanceBandsByIdData = {
    body?: ResistanceBand;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/ResistanceBands/{id}';
};

export type PutApiResistanceBandsByIdResponses = {
    /**
     * OK
     */
    200: ResistanceBand;
};

export type PutApiResistanceBandsByIdResponse = PutApiResistanceBandsByIdResponses[keyof PutApiResistanceBandsByIdResponses];

export type GetApiTargetAreasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/TargetAreas';
};

export type GetApiTargetAreasResponses = {
    /**
     * OK
     */
    200: Array<TargetArea>;
};

export type GetApiTargetAreasResponse = GetApiTargetAreasResponses[keyof GetApiTargetAreasResponses];

export type PostApiTargetAreasData = {
    body?: TargetArea;
    path?: never;
    query?: never;
    url: '/api/TargetAreas';
};

export type PostApiTargetAreasResponses = {
    /**
     * OK
     */
    200: TargetArea;
};

export type PostApiTargetAreasResponse = PostApiTargetAreasResponses[keyof PostApiTargetAreasResponses];

export type DeleteApiTargetAreasByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/TargetAreas/{id}';
};

export type DeleteApiTargetAreasByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTargetAreasByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/TargetAreas/{id}';
};

export type GetApiTargetAreasByIdResponses = {
    /**
     * OK
     */
    200: TargetArea;
};

export type GetApiTargetAreasByIdResponse = GetApiTargetAreasByIdResponses[keyof GetApiTargetAreasByIdResponses];

export type PutApiTargetAreasByIdData = {
    body?: TargetArea;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/TargetAreas/{id}';
};

export type PutApiTargetAreasByIdResponses = {
    /**
     * OK
     */
    200: TargetArea;
};

export type PutApiTargetAreasByIdResponse = PutApiTargetAreasByIdResponses[keyof PutApiTargetAreasByIdResponses];

export type GetApiUsersByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Users/{publicId}';
};

export type GetApiUsersByPublicIdResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetApiUsersByPublicIdResponse = GetApiUsersByPublicIdResponses[keyof GetApiUsersByPublicIdResponses];

export type GetApiUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users';
};

export type GetApiUsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetApiUsersResponse = GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
    body?: UserWritable;
    path?: never;
    query?: {
        setAuditFields?: boolean;
    };
    url: '/api/Users';
};

export type PostApiUsersResponses = {
    /**
     * OK
     */
    200: User;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];

export type PostApiUsersNewData = {
    body?: UserNewDto;
    path?: never;
    query?: never;
    url: '/api/Users/new';
};

export type PostApiUsersNewResponses = {
    /**
     * OK
     */
    200: User;
};

export type PostApiUsersNewResponse = PostApiUsersNewResponses[keyof PostApiUsersNewResponses];

export type GetApiUsersOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users/overview';
};

export type GetApiUsersOverviewResponses = {
    /**
     * OK
     */
    200: UserOverview;
};

export type GetApiUsersOverviewResponse = GetApiUsersOverviewResponses[keyof GetApiUsersOverviewResponses];

export type DeleteApiUsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type DeleteApiUsersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type GetApiUsersByIdResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetApiUsersByIdResponse = GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PutApiUsersByIdData = {
    body?: UserWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type PutApiUsersByIdResponses = {
    /**
     * OK
     */
    200: User;
};

export type PutApiUsersByIdResponse = PutApiUsersByIdResponses[keyof PutApiUsersByIdResponses];

export type GetApiWorkoutsData = {
    body?: never;
    path?: never;
    query?: {
        firstRecord?: number;
        pageSize?: number;
        activeOnly?: boolean;
        sortAscending?: boolean;
        nameContains?: string;
    };
    url: '/api/Workouts';
};

export type GetApiWorkoutsResponses = {
    /**
     * OK
     */
    200: WorkoutDtoPaginatedResults;
};

export type GetApiWorkoutsResponse = GetApiWorkoutsResponses[keyof GetApiWorkoutsResponses];

export type PostApiWorkoutsData = {
    body?: Workout;
    path?: never;
    query?: never;
    url: '/api/Workouts';
};

export type PostApiWorkoutsResponses = {
    /**
     * OK
     */
    200: Workout;
};

export type PostApiWorkoutsResponse = PostApiWorkoutsResponses[keyof PostApiWorkoutsResponses];

export type PutApiWorkoutsData = {
    body?: Workout;
    path?: never;
    query?: never;
    url: '/api/Workouts';
};

export type PutApiWorkoutsResponses = {
    /**
     * OK
     */
    200: Workout;
};

export type PutApiWorkoutsResponse = PutApiWorkoutsResponses[keyof PutApiWorkoutsResponses];

export type DeleteApiWorkoutsByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Workouts/{publicId}';
};

export type DeleteApiWorkoutsByPublicIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiWorkoutsByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Workouts/{publicId}';
};

export type GetApiWorkoutsByPublicIdResponses = {
    /**
     * OK
     */
    200: Workout;
};

export type GetApiWorkoutsByPublicIdResponse = GetApiWorkoutsByPublicIdResponses[keyof GetApiWorkoutsByPublicIdResponses];

export type GetApiWorkoutsByWorkoutPublicIdPlanData = {
    body?: never;
    path: {
        workoutPublicId: string;
    };
    query?: never;
    url: '/api/Workouts/{workoutPublicId}/plan';
};

export type GetApiWorkoutsByWorkoutPublicIdPlanResponses = {
    /**
     * OK
     */
    200: WorkoutPlan;
};

export type GetApiWorkoutsByWorkoutPublicIdPlanResponse = GetApiWorkoutsByWorkoutPublicIdPlanResponses[keyof GetApiWorkoutsByWorkoutPublicIdPlanResponses];

export type PostApiWorkoutsPlanData = {
    body?: WorkoutPlan;
    path?: never;
    query?: never;
    url: '/api/Workouts/plan';
};

export type PostApiWorkoutsPlanResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiWorkoutsPlanResponse = PostApiWorkoutsPlanResponses[keyof PostApiWorkoutsPlanResponses];

export type PostApiWorkoutsPlanForLaterData = {
    body?: WorkoutPlan;
    path?: never;
    query?: never;
    url: '/api/Workouts/plan-for-later';
};

export type PostApiWorkoutsPlanForLaterResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiWorkoutsPlanForLaterResponse = PostApiWorkoutsPlanForLaterResponses[keyof PostApiWorkoutsPlanForLaterResponses];

export type PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeData = {
    body?: WorkoutPlan;
    path: {
        startDateTime: Date;
        endDateTime: Date;
    };
    query?: never;
    url: '/api/Workouts/plan-for-past/{startDateTime}/{endDateTime}';
};

export type PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeResponse = PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeResponses[keyof PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeResponses];

export type PutApiWorkoutsByPublicIdRetireData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Workouts/{publicId}/retire';
};

export type PutApiWorkoutsByPublicIdRetireResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiWorkoutsByPublicIdReactivateData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Workouts/{publicId}/reactivate';
};

export type PutApiWorkoutsByPublicIdReactivateResponses = {
    /**
     * OK
     */
    200: unknown;
};
