// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5600' | (string & {});
};

export type AuthTokenResultDTO = {
    accessToken: string;
    refreshToken: string;
};

export type ExecutedExerciseDTO = {
    id: number;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name: string;
    exerciseId: string;
    resistanceType: ResistanceType;
    sequence: number;
    targetRepCount: number;
    actualRepCount: number;
    notes?: string | null;
    resistanceAmount: number;
    resistanceMakeup?: string | null;
    setType: SetType;
    duration?: number | null;
    formRating: number;
    rangeOfMotionRating: number;
    bandsEndToEnd?: boolean | null;
    involvesReps: boolean;
    side?: ExerciseSide | null;
    usesBilateralResistance: boolean;
};

export type ExecutedExerciseMetrics = {
    exerciseId: string;
    name: string;
    sequence: number;
    setType: SetType;
    averageRepCount: number;
    averageResistanceAmount: number;
    averageForm: number;
    averageRangeOfMotion: number;
};

export type ExecutedWorkoutDTO = {
    id: string;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name: string;
    workoutId: string;
    startDateTime?: Date | null;
    endDateTime?: Date | null;
    journal?: string | null;
    rating: number;
    exercises: Array<ExecutedExerciseDTO>;
};

export type ExecutedWorkoutMetrics = {
    name: string;
    startDateTime: Date;
    endDateTime: Date;
    exerciseMetrics: Array<ExecutedExerciseMetrics>;
};

export type ExecutedWorkoutSummaryDTO = {
    id: string;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name: string;
    workoutPublicId: string;
    startDateTime?: Date | null;
    endDateTime?: Date | null;
    journal?: string | null;
};

export type ExecutedWorkoutSummaryDTOPaginatedResults = {
    results: Array<ExecutedWorkoutSummaryDTO>;
    totalCount: number;
};

export type ExecutedWorkoutsSummary = {
    totalLoggedWorkouts: number;
    firstLoggedWorkoutDateTime?: Date | null;
    targetAreasWithWorkoutCounts: {
        [key: string]: number;
    };
};

export type Exercise = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name: string;
    publicId: string;
    description: string;
    setup: string;
    movement: string;
    pointsToRemember: string;
    exerciseTargetAreaLinks: Array<ExerciseTargetAreaLink>;
    resistanceType: ResistanceType;
    oneSided: boolean;
    bandsEndToEnd?: boolean | null;
    involvesReps: boolean;
    usesBilateralResistance: boolean;
};

export type ExerciseDTO = {
    id: number;
    publicId: string;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name: string;
    targetAreas: string;
};

export type ExerciseDTOPaginatedResults = {
    results: Array<ExerciseDTO>;
    totalCount: number;
};

export type ExerciseInWorkout = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    exercise?: Exercise | null;
    exerciseId: number;
    numberOfSets: number;
    setType: SetType;
    sequence: number;
};

export type ExerciseInWorkoutDTO = {
    id: number;
    exerciseId: string;
    exerciseName: string;
    numberOfSets: number;
    setType: SetType;
    resistanceType: ResistanceType;
};

export type ExercisePlan = {
    exerciseInWorkoutId: number;
    exerciseId: number;
    exerciseName: string;
    numberOfSets: number;
    setType: SetType;
    resistanceType: ResistanceType;
    sequence: number;
    targetRepCountLastTime: number;
    maxActualRepCountLastTime: number;
    avgActualRepCountLastTime: number;
    maxRangeOfMotionLastTime: number;
    avgRangeOfMotionLastTime: number;
    maxFormLastTime: number;
    avgFormLastTime: number;
    recommendedTargetRepCount?: number | null;
    targetRepCount: number;
    resistanceAmountLastTime: number;
    resistanceMakeupLastTime?: string | null;
    recommendedResistanceAmount?: number | null;
    recommendedResistanceMakeup?: string | null;
    resistanceAmount: number;
    resistanceMakeup?: string | null;
    bandsEndToEnd?: boolean | null;
    involvesReps: boolean;
    usesBilateralResistance: boolean;
    recommendationReason?: string | null;
};

export const ExerciseSide = { /**
     * Left
     */
    LEFT: 0, /**
     * Right
     */
    RIGHT: 1 } as const;

export type ExerciseSide = typeof ExerciseSide[keyof typeof ExerciseSide];

export type ExerciseTargetAreaLink = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    exerciseId: number;
    targetAreaId: number;
    exercise?: Exercise | null;
    targetArea?: TargetArea | null;
};

export type PasswordChangeRequest = {
    currentPassword: string;
    newPassword: string;
};

export type PasswordResetRequest = {
    resetCode: string;
    newPassword: string;
};

export type RefreshTokenRequestDTO = {
    accessToken: string;
    refreshToken: string;
};

export type RequestPasswordResetRequest = {
    emailAddress: string;
};

export type ResistanceBand = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    color: string;
    maxResistanceAmount: number;
    numberAvailable: number;
    publicId: string;
};

export const ResistanceType = {
    /**
     * FreeWeight
     */
    FREE_WEIGHT: 0,
    /**
     * MachineWeight
     */
    MACHINE_WEIGHT: 1,
    /**
     * ResistanceBand
     */
    RESISTANCE_BAND: 2,
    /**
     * BodyWeight
     */
    BODY_WEIGHT: 3,
    /**
     * Other
     */
    OTHER: 4
} as const;

export type ResistanceType = typeof ResistanceType[keyof typeof ResistanceType];

export const SetType = { /**
     * Repetition
     */
    REPETITION: 0, /**
     * Timed
     */
    TIMED: 1 } as const;

export type SetType = typeof SetType[keyof typeof SetType];

export type TargetArea = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name: string;
};

export type User = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name: string;
    publicId: string;
    emailAddress: string;
    hashedPassword?: string | null;
    profilePic?: string | null;
    settings: UserSettings;
    role: UserRole;
    salt?: string | null;
    passwordResetCode?: string | null;
    readonly passwordProtected: boolean;
};

export type UserCredentialsDTO = {
    username: string;
    password: string;
};

export type UserMinMaxReps = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    userSettingsId: number;
    setType: SetType;
    duration?: number | null;
    minReps: number;
    maxReps: number;
};

export type UserNewDTO = {
    userName: string;
    emailAddress: string;
    password: string;
    role: UserRole;
};

export type UserOverview = {
    username: string;
    lastWorkoutDateTime?: Date | null;
    plannedWorkoutCount: number;
};

export const UserRole = { /**
     * Standard
     */
    STANDARD: 1, /**
     * Administrator
     */
    ADMINISTRATOR: 2 } as const;

export type UserRole = typeof UserRole[keyof typeof UserRole];

export type UserSettings = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    userId: number;
    repSettings: Array<UserMinMaxReps>;
    recommendationsEnabled: boolean;
    lowestAcceptableRating: number;
};

export type Workout = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name: string;
    publicId: string;
    exercises: Array<ExerciseInWorkout>;
    active: boolean;
};

export type WorkoutDTO = {
    id: string;
    createdDateTime: Date;
    modifiedDateTime?: Date | null;
    name: string;
    exercises: Array<ExerciseInWorkoutDTO>;
    targetAreas: string;
    active: boolean;
};

export type WorkoutDTOPaginatedResults = {
    results: Array<WorkoutDTO>;
    totalCount: number;
};

export type WorkoutPlan = {
    workoutId: string;
    workoutName: string;
    hasBeenExecutedBefore: boolean;
    exercises: Array<ExercisePlan>;
    submittedDateTime?: Date | null;
};

export type UserWritable = {
    id: number;
    createdByUserId: number;
    createdDateTime: Date;
    modifiedByUserId?: number | null;
    modifiedDateTime?: Date | null;
    name: string;
    publicId: string;
    emailAddress: string;
    hashedPassword?: string | null;
    profilePic?: string | null;
    settings: UserSettings;
    role: UserRole;
    salt?: string | null;
    passwordResetCode?: string | null;
};

export type GetApiAnalyticsExecutedWorkoutsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Analytics/executed-workouts';
};

export type GetApiAnalyticsExecutedWorkoutsResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutsSummary;
};

export type GetApiAnalyticsExecutedWorkoutsResponse = GetApiAnalyticsExecutedWorkoutsResponses[keyof GetApiAnalyticsExecutedWorkoutsResponses];

export type GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountData = {
    body?: never;
    path: {
        workoutPublicId: string;
        count: number;
    };
    query?: never;
    url: '/api/Analytics/workout-metrics/{workoutPublicId}/{count}';
};

export type GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponses = {
    /**
     * OK
     */
    200: Array<ExecutedWorkoutMetrics>;
};

export type GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponse = GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponses[keyof GetApiAnalyticsWorkoutMetricsByWorkoutPublicIdByCountResponses];

export type PostApiAuthLoginData = {
    body?: UserCredentialsDTO;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthTokenResultDTO;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRefreshData = {
    body?: RefreshTokenRequestDTO;
    path?: never;
    query?: never;
    url: '/api/Auth/refresh';
};

export type PostApiAuthRefreshResponses = {
    /**
     * OK
     */
    200: AuthTokenResultDTO;
};

export type PostApiAuthRefreshResponse = PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];

export type PostApiAuthRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/revoke';
};

export type PostApiAuthRevokeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthChangePasswordData = {
    body?: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/change-password';
};

export type PostApiAuthChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthRequestPasswordResetData = {
    body?: RequestPasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/request-password-reset';
};

export type PostApiAuthRequestPasswordResetResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiAuthRequestPasswordResetResponse = PostApiAuthRequestPasswordResetResponses[keyof PostApiAuthRequestPasswordResetResponses];

export type PostApiAuthResetPasswordData = {
    body?: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/reset-password';
};

export type PostApiAuthResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAuthValidateResetCodeByResetCodeData = {
    body?: never;
    path: {
        resetCode: string;
    };
    query?: never;
    url: '/api/Auth/validate-reset-code/{resetCode}';
};

export type GetApiAuthValidateResetCodeByResetCodeResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetApiAuthValidateResetCodeByResetCodeResponse = GetApiAuthValidateResetCodeByResetCodeResponses[keyof GetApiAuthValidateResetCodeByResetCodeResponses];

export type GetApiExecutedWorkoutByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/ExecutedWorkout/{publicId}';
};

export type GetApiExecutedWorkoutByPublicIdResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutDTO;
};

export type GetApiExecutedWorkoutByPublicIdResponse = GetApiExecutedWorkoutByPublicIdResponses[keyof GetApiExecutedWorkoutByPublicIdResponses];

export type PutApiExecutedWorkoutByIdData = {
    body?: ExecutedWorkoutDTO;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ExecutedWorkout/{id}';
};

export type PutApiExecutedWorkoutByIdResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutDTO;
};

export type PutApiExecutedWorkoutByIdResponse = PutApiExecutedWorkoutByIdResponses[keyof PutApiExecutedWorkoutByIdResponses];

export type GetApiExecutedWorkoutData = {
    body?: never;
    path?: never;
    query?: {
        firstRecord?: number;
        pageSize?: number;
        startDateTime?: Date;
        endDateTime?: Date;
        newestFirst?: boolean;
        workoutNameContains?: string;
        onlyWithJournalNotes?: boolean;
    };
    url: '/api/ExecutedWorkout';
};

export type GetApiExecutedWorkoutResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutSummaryDTOPaginatedResults;
};

export type GetApiExecutedWorkoutResponse = GetApiExecutedWorkoutResponses[keyof GetApiExecutedWorkoutResponses];

export type GetApiExecutedWorkoutPlannedData = {
    body?: never;
    path?: never;
    query?: {
        firstRecord?: number;
        pageSize?: number;
        newestFirst?: boolean;
    };
    url: '/api/ExecutedWorkout/planned';
};

export type GetApiExecutedWorkoutPlannedResponses = {
    /**
     * OK
     */
    200: ExecutedWorkoutSummaryDTOPaginatedResults;
};

export type GetApiExecutedWorkoutPlannedResponse = GetApiExecutedWorkoutPlannedResponses[keyof GetApiExecutedWorkoutPlannedResponses];

export type GetApiExecutedWorkoutInProgressData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ExecutedWorkout/in-progress';
};

export type GetApiExecutedWorkoutInProgressResponses = {
    /**
     * OK
     */
    200: Array<ExecutedWorkoutSummaryDTO>;
};

export type GetApiExecutedWorkoutInProgressResponse = GetApiExecutedWorkoutInProgressResponses[keyof GetApiExecutedWorkoutInProgressResponses];

export type DeleteApiExecutedWorkoutPlannedByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/ExecutedWorkout/planned/{publicId}';
};

export type DeleteApiExecutedWorkoutPlannedByPublicIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiExercisesData = {
    body?: never;
    path?: never;
    query?: {
        firstRecord?: number;
        pageSize?: number;
        nameContains?: string;
        hasTargetAreas?: string;
    };
    url: '/api/Exercises';
};

export type GetApiExercisesResponses = {
    /**
     * OK
     */
    200: ExerciseDTOPaginatedResults;
};

export type GetApiExercisesResponse = GetApiExercisesResponses[keyof GetApiExercisesResponses];

export type PostApiExercisesData = {
    body?: Exercise;
    path?: never;
    query?: never;
    url: '/api/Exercises';
};

export type PostApiExercisesResponses = {
    /**
     * OK
     */
    200: Exercise;
};

export type PostApiExercisesResponse = PostApiExercisesResponses[keyof PostApiExercisesResponses];

export type PutApiExercisesData = {
    body?: Exercise;
    path?: never;
    query?: never;
    url: '/api/Exercises';
};

export type PutApiExercisesResponses = {
    /**
     * OK
     */
    200: Exercise;
};

export type PutApiExercisesResponse = PutApiExercisesResponses[keyof PutApiExercisesResponses];

export type DeleteApiExercisesByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Exercises/{publicId}';
};

export type DeleteApiExercisesByPublicIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiExercisesByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Exercises/{publicId}';
};

export type GetApiExercisesByPublicIdResponses = {
    /**
     * OK
     */
    200: Exercise;
};

export type GetApiExercisesByPublicIdResponse = GetApiExercisesByPublicIdResponses[keyof GetApiExercisesByPublicIdResponses];

export type GetApiExercisesResistanceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Exercises/ResistanceTypes';
};

export type GetApiExercisesResistanceTypesResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetApiExercisesResistanceTypesResponse = GetApiExercisesResistanceTypesResponses[keyof GetApiExercisesResistanceTypesResponses];

export type GetApiResistanceBandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ResistanceBands';
};

export type GetApiResistanceBandsResponses = {
    /**
     * OK
     */
    200: Array<ResistanceBand>;
};

export type GetApiResistanceBandsResponse = GetApiResistanceBandsResponses[keyof GetApiResistanceBandsResponses];

export type PostApiResistanceBandsData = {
    body?: ResistanceBand;
    path?: never;
    query?: {
        setAuditFields?: boolean;
    };
    url: '/api/ResistanceBands';
};

export type PostApiResistanceBandsResponses = {
    /**
     * OK
     */
    200: ResistanceBand;
};

export type PostApiResistanceBandsResponse = PostApiResistanceBandsResponses[keyof PostApiResistanceBandsResponses];

export type DeleteApiResistanceBandsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/ResistanceBands/{id}';
};

export type DeleteApiResistanceBandsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiResistanceBandsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/ResistanceBands/{id}';
};

export type GetApiResistanceBandsByIdResponses = {
    /**
     * OK
     */
    200: ResistanceBand;
};

export type GetApiResistanceBandsByIdResponse = GetApiResistanceBandsByIdResponses[keyof GetApiResistanceBandsByIdResponses];

export type PutApiResistanceBandsByIdData = {
    body?: ResistanceBand;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/ResistanceBands/{id}';
};

export type PutApiResistanceBandsByIdResponses = {
    /**
     * OK
     */
    200: ResistanceBand;
};

export type PutApiResistanceBandsByIdResponse = PutApiResistanceBandsByIdResponses[keyof PutApiResistanceBandsByIdResponses];

export type GetApiTargetAreasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/TargetAreas';
};

export type GetApiTargetAreasResponses = {
    /**
     * OK
     */
    200: Array<TargetArea>;
};

export type GetApiTargetAreasResponse = GetApiTargetAreasResponses[keyof GetApiTargetAreasResponses];

export type PostApiTargetAreasData = {
    body?: TargetArea;
    path?: never;
    query?: never;
    url: '/api/TargetAreas';
};

export type PostApiTargetAreasResponses = {
    /**
     * OK
     */
    200: TargetArea;
};

export type PostApiTargetAreasResponse = PostApiTargetAreasResponses[keyof PostApiTargetAreasResponses];

export type DeleteApiTargetAreasByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/TargetAreas/{id}';
};

export type DeleteApiTargetAreasByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTargetAreasByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/TargetAreas/{id}';
};

export type GetApiTargetAreasByIdResponses = {
    /**
     * OK
     */
    200: TargetArea;
};

export type GetApiTargetAreasByIdResponse = GetApiTargetAreasByIdResponses[keyof GetApiTargetAreasByIdResponses];

export type PutApiTargetAreasByIdData = {
    body?: TargetArea;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/TargetAreas/{id}';
};

export type PutApiTargetAreasByIdResponses = {
    /**
     * OK
     */
    200: TargetArea;
};

export type PutApiTargetAreasByIdResponse = PutApiTargetAreasByIdResponses[keyof PutApiTargetAreasByIdResponses];

export type GetApiUsersByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Users/{publicId}';
};

export type GetApiUsersByPublicIdResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetApiUsersByPublicIdResponse = GetApiUsersByPublicIdResponses[keyof GetApiUsersByPublicIdResponses];

export type GetApiUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users';
};

export type GetApiUsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetApiUsersResponse = GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
    body?: UserWritable;
    path?: never;
    query?: {
        setAuditFields?: boolean;
    };
    url: '/api/Users';
};

export type PostApiUsersResponses = {
    /**
     * OK
     */
    200: User;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];

export type PostApiUsersNewData = {
    body?: UserNewDTO;
    path?: never;
    query?: never;
    url: '/api/Users/new';
};

export type PostApiUsersNewResponses = {
    /**
     * OK
     */
    200: User;
};

export type PostApiUsersNewResponse = PostApiUsersNewResponses[keyof PostApiUsersNewResponses];

export type GetApiUsersOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users/overview';
};

export type GetApiUsersOverviewResponses = {
    /**
     * OK
     */
    200: UserOverview;
};

export type GetApiUsersOverviewResponse = GetApiUsersOverviewResponses[keyof GetApiUsersOverviewResponses];

export type DeleteApiUsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type DeleteApiUsersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type GetApiUsersByIdResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetApiUsersByIdResponse = GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PutApiUsersByIdData = {
    body?: UserWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type PutApiUsersByIdResponses = {
    /**
     * OK
     */
    200: User;
};

export type PutApiUsersByIdResponse = PutApiUsersByIdResponses[keyof PutApiUsersByIdResponses];

export type GetApiWorkoutsData = {
    body?: never;
    path?: never;
    query?: {
        firstRecord?: number;
        pageSize?: number;
        activeOnly?: boolean;
        sortAscending?: boolean;
        nameContains?: string;
    };
    url: '/api/Workouts';
};

export type GetApiWorkoutsResponses = {
    /**
     * OK
     */
    200: WorkoutDTOPaginatedResults;
};

export type GetApiWorkoutsResponse = GetApiWorkoutsResponses[keyof GetApiWorkoutsResponses];

export type PostApiWorkoutsData = {
    body?: Workout;
    path?: never;
    query?: never;
    url: '/api/Workouts';
};

export type PostApiWorkoutsResponses = {
    /**
     * OK
     */
    200: Workout;
};

export type PostApiWorkoutsResponse = PostApiWorkoutsResponses[keyof PostApiWorkoutsResponses];

export type PutApiWorkoutsData = {
    body?: Workout;
    path?: never;
    query?: never;
    url: '/api/Workouts';
};

export type PutApiWorkoutsResponses = {
    /**
     * OK
     */
    200: Workout;
};

export type PutApiWorkoutsResponse = PutApiWorkoutsResponses[keyof PutApiWorkoutsResponses];

export type DeleteApiWorkoutsByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Workouts/{publicId}';
};

export type DeleteApiWorkoutsByPublicIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiWorkoutsByPublicIdData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Workouts/{publicId}';
};

export type GetApiWorkoutsByPublicIdResponses = {
    /**
     * OK
     */
    200: Workout;
};

export type GetApiWorkoutsByPublicIdResponse = GetApiWorkoutsByPublicIdResponses[keyof GetApiWorkoutsByPublicIdResponses];

export type GetApiWorkoutsByWorkoutPublicIdPlanData = {
    body?: never;
    path: {
        workoutPublicId: string;
    };
    query?: never;
    url: '/api/Workouts/{workoutPublicId}/plan';
};

export type GetApiWorkoutsByWorkoutPublicIdPlanResponses = {
    /**
     * OK
     */
    200: WorkoutPlan;
};

export type GetApiWorkoutsByWorkoutPublicIdPlanResponse = GetApiWorkoutsByWorkoutPublicIdPlanResponses[keyof GetApiWorkoutsByWorkoutPublicIdPlanResponses];

export type PostApiWorkoutsPlanData = {
    body?: WorkoutPlan;
    path?: never;
    query?: never;
    url: '/api/Workouts/plan';
};

export type PostApiWorkoutsPlanResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiWorkoutsPlanResponse = PostApiWorkoutsPlanResponses[keyof PostApiWorkoutsPlanResponses];

export type PostApiWorkoutsPlanForLaterData = {
    body?: WorkoutPlan;
    path?: never;
    query?: never;
    url: '/api/Workouts/plan-for-later';
};

export type PostApiWorkoutsPlanForLaterResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiWorkoutsPlanForLaterResponse = PostApiWorkoutsPlanForLaterResponses[keyof PostApiWorkoutsPlanForLaterResponses];

export type PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeData = {
    body?: WorkoutPlan;
    path: {
        startDateTime: Date;
        endDateTime: Date;
    };
    query?: never;
    url: '/api/Workouts/plan-for-past/{startDateTime}/{endDateTime}';
};

export type PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeResponse = PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeResponses[keyof PostApiWorkoutsPlanForPastByStartDateTimeByEndDateTimeResponses];

export type PutApiWorkoutsByPublicIdRetireData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Workouts/{publicId}/retire';
};

export type PutApiWorkoutsByPublicIdRetireResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiWorkoutsByPublicIdReactivateData = {
    body?: never;
    path: {
        publicId: string;
    };
    query?: never;
    url: '/api/Workouts/{publicId}/reactivate';
};

export type PutApiWorkoutsByPublicIdReactivateResponses = {
    /**
     * OK
     */
    200: unknown;
};
